spring:
  flyway:
    locations: classpath:db/migration/{vendor}
  webflux:
    date-format: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://${database.host}:${database.port:3306}/${database.schema.name}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: ${database.username}
    password: ${database.password}
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org.quartz.plugin.jobHistory.class: org.quartz.plugins.history.LoggingJobHistoryPlugin
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.isClustered: false
  messages:
    basename: message/app-message

management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"

