/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elegant.model.jooq.Indexes;
import org.elegant.model.jooq.Keys;
import org.elegant.model.jooq.Public;
import org.elegant.model.jooq.tables.records.DirectoryPathRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryPath extends TableImpl<DirectoryPathRecord> {

    private static final long serialVersionUID = 6307973;

    /**
     * The reference instance of <code>PUBLIC.directory_path</code>
     */
    public static final DirectoryPath DIRECTORY_PATH = new DirectoryPath();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DirectoryPathRecord> getRecordType() {
        return DirectoryPathRecord.class;
    }

    /**
     * The column <code>PUBLIC.directory_path.ancestor</code>. 祖先目录id
     */
    public final TableField<DirectoryPathRecord, Integer> ANCESTOR = createField("ancestor", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "祖先目录id");

    /**
     * The column <code>PUBLIC.directory_path.dir_id</code>. 后代目录id
     */
    public final TableField<DirectoryPathRecord, Integer> DIR_ID = createField("dir_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "后代目录id");

    /**
     * The column <code>PUBLIC.directory_path.path_length</code>. 目录的深度
     */
    public final TableField<DirectoryPathRecord, Integer> PATH_LENGTH = createField("path_length", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "目录的深度");

    /**
     * The column <code>PUBLIC.directory_path.create_time</code>. 创建时间
     */
    public final TableField<DirectoryPathRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>PUBLIC.directory_path.update_time</code>.
     */
    public final TableField<DirectoryPathRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>PUBLIC.directory_path</code> table reference
     */
    public DirectoryPath() {
        this(DSL.name("directory_path"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.directory_path</code> table reference
     */
    public DirectoryPath(String alias) {
        this(DSL.name(alias), DIRECTORY_PATH);
    }

    /**
     * Create an aliased <code>PUBLIC.directory_path</code> table reference
     */
    public DirectoryPath(Name alias) {
        this(alias, DIRECTORY_PATH);
    }

    private DirectoryPath(Name alias, Table<DirectoryPathRecord> aliased) {
        this(alias, aliased, null);
    }

    private DirectoryPath(Name alias, Table<DirectoryPathRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> DirectoryPath(Table<O> child, ForeignKey<O, DirectoryPathRecord> key) {
        super(child, key, DIRECTORY_PATH);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DirectoryPathRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DirectoryPathRecord>> getKeys() {
        return Arrays.<UniqueKey<DirectoryPathRecord>>asList(Keys.CONSTRAINT_4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DirectoryPath as(String alias) {
        return new DirectoryPath(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DirectoryPath as(Name alias) {
        return new DirectoryPath(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DirectoryPath rename(String name) {
        return new DirectoryPath(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DirectoryPath rename(Name name) {
        return new DirectoryPath(name, null);
    }
}
