/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elegant.model.jooq.Indexes;
import org.elegant.model.jooq.Keys;
import org.elegant.model.jooq.Public;
import org.elegant.model.jooq.tables.records.PropertyRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Property extends TableImpl<PropertyRecord> {

    private static final long serialVersionUID = 1571753133;

    /**
     * The reference instance of <code>PUBLIC.property</code>
     */
    public static final Property PROPERTY = new Property();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PropertyRecord> getRecordType() {
        return PropertyRecord.class;
    }

    /**
     * The column <code>PUBLIC.property.prop_name</code>. 属性名称
     */
    public final TableField<PropertyRecord, String> PROP_NAME = createField("prop_name", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "属性名称");

    /**
     * The column <code>PUBLIC.property.prop_value</code>. 属性值
     */
    public final TableField<PropertyRecord, String> PROP_VALUE = createField("prop_value", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "属性值");

    /**
     * The column <code>PUBLIC.property.create_time</code>. 创建时间
     */
    public final TableField<PropertyRecord, LocalDateTime> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>PUBLIC.property.update_time</code>.
     */
    public final TableField<PropertyRecord, LocalDateTime> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.LOCALDATETIME.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP()", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * Create a <code>PUBLIC.property</code> table reference
     */
    public Property() {
        this(DSL.name("property"), null);
    }

    /**
     * Create an aliased <code>PUBLIC.property</code> table reference
     */
    public Property(String alias) {
        this(DSL.name(alias), PROPERTY);
    }

    /**
     * Create an aliased <code>PUBLIC.property</code> table reference
     */
    public Property(Name alias) {
        this(alias, PROPERTY);
    }

    private Property(Name alias, Table<PropertyRecord> aliased) {
        this(alias, aliased, null);
    }

    private Property(Name alias, Table<PropertyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Property(Table<O> child, ForeignKey<O, PropertyRecord> key) {
        super(child, key, PROPERTY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_C4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PropertyRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PropertyRecord>> getKeys() {
        return Arrays.<UniqueKey<PropertyRecord>>asList(Keys.CONSTRAINT_C4);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Property as(String alias) {
        return new Property(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Property as(Name alias) {
        return new Property(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Property rename(String name) {
        return new Property(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Property rename(Name name) {
        return new Property(name, null);
    }
}
