/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq;


import javax.annotation.Generated;

import org.elegant.model.jooq.tables.Author;
import org.elegant.model.jooq.tables.AuthorBookRelation;
import org.elegant.model.jooq.tables.Book;
import org.elegant.model.jooq.tables.BookCover;
import org.elegant.model.jooq.tables.Directory;
import org.elegant.model.jooq.tables.DirectoryPath;
import org.elegant.model.jooq.tables.Media;
import org.elegant.model.jooq.tables.Property;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_A = Indexes0.PRIMARY_KEY_A;
    public static final Index PRIMARY_KEY_6F = Indexes0.PRIMARY_KEY_6F;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index PRIMARY_KEY_9 = Indexes0.PRIMARY_KEY_9;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;
    public static final Index PRIMARY_KEY_4 = Indexes0.PRIMARY_KEY_4;
    public static final Index PRIMARY_KEY_62 = Indexes0.PRIMARY_KEY_62;
    public static final Index PRIMARY_KEY_C4 = Indexes0.PRIMARY_KEY_C4;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_A = Internal.createIndex("PRIMARY_KEY_A", Author.AUTHOR, new OrderField[] { Author.AUTHOR.AUTHOR_ID }, true);
        public static Index PRIMARY_KEY_6F = Internal.createIndex("PRIMARY_KEY_6F", AuthorBookRelation.AUTHOR_BOOK_RELATION, new OrderField[] { AuthorBookRelation.AUTHOR_BOOK_RELATION.BOOK_ID, AuthorBookRelation.AUTHOR_BOOK_RELATION.AUTHOR_ID }, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", Book.BOOK, new OrderField[] { Book.BOOK.BOOK_ID }, true);
        public static Index PRIMARY_KEY_9 = Internal.createIndex("PRIMARY_KEY_9", BookCover.BOOK_COVER, new OrderField[] { BookCover.BOOK_COVER.BOOK_ID }, true);
        public static Index PRIMARY_KEY_C = Internal.createIndex("PRIMARY_KEY_C", Directory.DIRECTORY, new OrderField[] { Directory.DIRECTORY.DIR_ID }, true);
        public static Index PRIMARY_KEY_4 = Internal.createIndex("PRIMARY_KEY_4", DirectoryPath.DIRECTORY_PATH, new OrderField[] { DirectoryPath.DIRECTORY_PATH.ANCESTOR, DirectoryPath.DIRECTORY_PATH.DIR_ID }, true);
        public static Index PRIMARY_KEY_62 = Internal.createIndex("PRIMARY_KEY_62", Media.MEDIA, new OrderField[] { Media.MEDIA.MEDIA_ID }, true);
        public static Index PRIMARY_KEY_C4 = Internal.createIndex("PRIMARY_KEY_C4", Property.PROPERTY, new OrderField[] { Property.PROPERTY.PROP_NAME }, true);
    }
}
