/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.elegant.model.jooq.tables.Author;
import org.elegant.model.jooq.tables.AuthorBookRelation;
import org.elegant.model.jooq.tables.Book;
import org.elegant.model.jooq.tables.BookCover;
import org.elegant.model.jooq.tables.Directory;
import org.elegant.model.jooq.tables.DirectoryPath;
import org.elegant.model.jooq.tables.Media;
import org.elegant.model.jooq.tables.Property;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -119084712;

    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>PUBLIC.author</code>.
     */
    public final Author AUTHOR = org.elegant.model.jooq.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.author_book_relation</code>.
     */
    public final AuthorBookRelation AUTHOR_BOOK_RELATION = org.elegant.model.jooq.tables.AuthorBookRelation.AUTHOR_BOOK_RELATION;

    /**
     * The table <code>PUBLIC.book</code>.
     */
    public final Book BOOK = org.elegant.model.jooq.tables.Book.BOOK;

    /**
     * The table <code>PUBLIC.book_cover</code>.
     */
    public final BookCover BOOK_COVER = org.elegant.model.jooq.tables.BookCover.BOOK_COVER;

    /**
     * The table <code>PUBLIC.directory</code>.
     */
    public final Directory DIRECTORY = org.elegant.model.jooq.tables.Directory.DIRECTORY;

    /**
     * The table <code>PUBLIC.directory_path</code>.
     */
    public final DirectoryPath DIRECTORY_PATH = org.elegant.model.jooq.tables.DirectoryPath.DIRECTORY_PATH;

    /**
     * The table <code>PUBLIC.media</code>.
     */
    public final Media MEDIA = org.elegant.model.jooq.tables.Media.MEDIA;

    /**
     * The table <code>PUBLIC.property</code>.
     */
    public final Property PROPERTY = org.elegant.model.jooq.tables.Property.PROPERTY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("PUBLIC", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            AuthorBookRelation.AUTHOR_BOOK_RELATION,
            Book.BOOK,
            BookCover.BOOK_COVER,
            Directory.DIRECTORY,
            DirectoryPath.DIRECTORY_PATH,
            Media.MEDIA,
            Property.PROPERTY);
    }
}
