/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.records;


import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.elegant.model.jooq.tables.Book;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record14<Integer, String, Integer, String, String, String, LocalDateTime, Short, Long, Long, Short, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -235039442;

    /**
     * Setter for <code>PUBLIC.book.book_id</code>. 书本id
     */
    public BookRecord setBookId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.book_id</code>. 书本id
     */
    public Integer getBookId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>PUBLIC.book.title</code>. 书本名称
     */
    public BookRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.title</code>. 书本名称
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.book.dir_id</code>. 书本所在目录
     */
    public BookRecord setDirId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.dir_id</code>. 书本所在目录
     */
    public Integer getDirId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>PUBLIC.book.language</code>. 书本使用的语言
     */
    public BookRecord setLanguage(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.language</code>. 书本使用的语言
     */
    public String getLanguage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.book.series</code>. 书本所属的系列
     */
    public BookRecord setSeries(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.series</code>. 书本所属的系列
     */
    public String getSeries() {
        return (String) get(4);
    }

    /**
     * Setter for <code>PUBLIC.book.publisher</code>. 出版社
     */
    public BookRecord setPublisher(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.publisher</code>. 出版社
     */
    public String getPublisher() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.book.publish_time</code>. 出版时间
     */
    public BookRecord setPublishTime(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.publish_time</code>. 出版时间
     */
    public LocalDateTime getPublishTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>PUBLIC.book.rating</code>. 评价
     */
    public BookRecord setRating(Short value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.rating</code>. 评价
     */
    public Short getRating() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>PUBLIC.book.isbn10</code>. isbn10
     */
    public BookRecord setIsbn10(Long value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.isbn10</code>. isbn10
     */
    public Long getIsbn10() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>PUBLIC.book.isbn13</code>. isbn13
     */
    public BookRecord setIsbn13(Long value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.isbn13</code>. isbn13
     */
    public Long getIsbn13() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>PUBLIC.book.page</code>. 页数
     */
    public BookRecord setPage(Short value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.page</code>. 页数
     */
    public Short getPage() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>PUBLIC.book.format</code>. 书本格式
     */
    public BookRecord setFormat(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.format</code>. 书本格式
     */
    public String getFormat() {
        return (String) get(11);
    }

    /**
     * Setter for <code>PUBLIC.book.create_time</code>. 创建时间
     */
    public BookRecord setCreateTime(LocalDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>PUBLIC.book.update_time</code>. 更新时间
     */
    public BookRecord setUpdateTime(LocalDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>PUBLIC.book.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, Integer, String, String, String, LocalDateTime, Short, Long, Long, Short, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, String, Integer, String, String, String, LocalDateTime, Short, Long, Long, Short, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Book.BOOK.BOOK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Book.BOOK.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Book.BOOK.DIR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Book.BOOK.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Book.BOOK.SERIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Book.BOOK.PUBLISHER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Book.BOOK.PUBLISH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Book.BOOK.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Book.BOOK.ISBN10;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return Book.BOOK.ISBN13;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field11() {
        return Book.BOOK.PAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Book.BOOK.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field13() {
        return Book.BOOK.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field14() {
        return Book.BOOK.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDirId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSeries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPublisher();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getPublishTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getIsbn10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getIsbn13();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component11() {
        return getPage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component13() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component14() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getBookId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDirId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSeries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPublisher();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getPublishTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getIsbn10();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getIsbn13();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value11() {
        return getPage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value13() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value14() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value1(Integer value) {
        setBookId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value3(Integer value) {
        setDirId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value4(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value5(String value) {
        setSeries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value6(String value) {
        setPublisher(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value7(LocalDateTime value) {
        setPublishTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value8(Short value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value9(Long value) {
        setIsbn10(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value10(Long value) {
        setIsbn13(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value11(Short value) {
        setPage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value12(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value13(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value14(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, LocalDateTime value7, Short value8, Long value9, Long value10, Short value11, String value12, LocalDateTime value13, LocalDateTime value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer bookId, String title, Integer dirId, String language, String series, String publisher, LocalDateTime publishTime, Short rating, Long isbn10, Long isbn13, Short page, String format, LocalDateTime createTime, LocalDateTime updateTime) {
        super(Book.BOOK);

        set(0, bookId);
        set(1, title);
        set(2, dirId);
        set(3, language);
        set(4, series);
        set(5, publisher);
        set(6, publishTime);
        set(7, rating);
        set(8, isbn10);
        set(9, isbn13);
        set(10, page);
        set(11, format);
        set(12, createTime);
        set(13, updateTime);
    }
}
