/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.elegant.model.jooq.tables.DirectoryPath;
import org.elegant.model.jooq.tables.records.DirectoryPathRecord;
import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryPathDao extends DAOImpl<DirectoryPathRecord, org.elegant.model.jooq.tables.pojos.DirectoryPath, Record2<Integer, Integer>> {

    /**
     * Create a new DirectoryPathDao without any configuration
     */
    public DirectoryPathDao() {
        super(DirectoryPath.DIRECTORY_PATH, org.elegant.model.jooq.tables.pojos.DirectoryPath.class);
    }

    /**
     * Create a new DirectoryPathDao with an attached configuration
     */
    public DirectoryPathDao(Configuration configuration) {
        super(DirectoryPath.DIRECTORY_PATH, org.elegant.model.jooq.tables.pojos.DirectoryPath.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, Integer> getId(org.elegant.model.jooq.tables.pojos.DirectoryPath object) {
        return compositeKeyRecord(object.getAncestor(), object.getDirId());
    }

    /**
     * Fetch records that have <code>ancestor IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.DirectoryPath> fetchByAncestor(Integer... values) {
        return fetch(DirectoryPath.DIRECTORY_PATH.ANCESTOR, values);
    }

    /**
     * Fetch records that have <code>dir_id IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.DirectoryPath> fetchByDirId(Integer... values) {
        return fetch(DirectoryPath.DIRECTORY_PATH.DIR_ID, values);
    }

    /**
     * Fetch records that have <code>path_length IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.DirectoryPath> fetchByPathLength(Integer... values) {
        return fetch(DirectoryPath.DIRECTORY_PATH.PATH_LENGTH, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.DirectoryPath> fetchByCreateTime(LocalDateTime... values) {
        return fetch(DirectoryPath.DIRECTORY_PATH.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.DirectoryPath> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(DirectoryPath.DIRECTORY_PATH.UPDATE_TIME, values);
    }
}
