/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.daos;


import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.elegant.model.jooq.tables.Directory;
import org.elegant.model.jooq.tables.records.DirectoryRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryDao extends DAOImpl<DirectoryRecord, org.elegant.model.jooq.tables.pojos.Directory, Integer> {

    /**
     * Create a new DirectoryDao without any configuration
     */
    public DirectoryDao() {
        super(Directory.DIRECTORY, org.elegant.model.jooq.tables.pojos.Directory.class);
    }

    /**
     * Create a new DirectoryDao with an attached configuration
     */
    public DirectoryDao(Configuration configuration) {
        super(Directory.DIRECTORY, org.elegant.model.jooq.tables.pojos.Directory.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(org.elegant.model.jooq.tables.pojos.Directory object) {
        return object.getDirId();
    }

    /**
     * Fetch records that have <code>dir_id IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.Directory> fetchByDirId(Integer... values) {
        return fetch(Directory.DIRECTORY.DIR_ID, values);
    }

    /**
     * Fetch a unique record that has <code>dir_id = value</code>
     */
    public org.elegant.model.jooq.tables.pojos.Directory fetchOneByDirId(Integer value) {
        return fetchOne(Directory.DIRECTORY.DIR_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.Directory> fetchByName(String... values) {
        return fetch(Directory.DIRECTORY.NAME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.Directory> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Directory.DIRECTORY.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<org.elegant.model.jooq.tables.pojos.Directory> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(Directory.DIRECTORY.UPDATE_TIME, values);
    }
}
