/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorBookRelation implements Serializable {

    private static final long serialVersionUID = 166091397;

    private Integer       bookId;
    private Integer       authorId;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public AuthorBookRelation() {}

    public AuthorBookRelation(AuthorBookRelation value) {
        this.bookId = value.bookId;
        this.authorId = value.authorId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public AuthorBookRelation(
        Integer       bookId,
        Integer       authorId,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.bookId = bookId;
        this.authorId = authorId;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public AuthorBookRelation setBookId(Integer bookId) {
        this.bookId = bookId;
        return this;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public AuthorBookRelation setAuthorId(Integer authorId) {
        this.authorId = authorId;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public AuthorBookRelation setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public AuthorBookRelation setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AuthorBookRelation (");

        sb.append(bookId);
        sb.append(", ").append(authorId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
