/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookCover implements Serializable {

    private static final long serialVersionUID = -1400474381;

    private Integer bookId;
    private byte[]  cover;
    private String  imageFileExtension;

    public BookCover() {}

    public BookCover(BookCover value) {
        this.bookId = value.bookId;
        this.cover = value.cover;
        this.imageFileExtension = value.imageFileExtension;
    }

    public BookCover(
        Integer bookId,
        byte[]  cover,
        String  imageFileExtension
    ) {
        this.bookId = bookId;
        this.cover = cover;
        this.imageFileExtension = imageFileExtension;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public BookCover setBookId(Integer bookId) {
        this.bookId = bookId;
        return this;
    }

    public byte[] getCover() {
        return this.cover;
    }

    public BookCover setCover(byte... cover) {
        this.cover = cover;
        return this;
    }

    public String getImageFileExtension() {
        return this.imageFileExtension;
    }

    public BookCover setImageFileExtension(String imageFileExtension) {
        this.imageFileExtension = imageFileExtension;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BookCover (");

        sb.append(bookId);
        sb.append(", ").append("[binary...]");
        sb.append(", ").append(imageFileExtension);

        sb.append(")");
        return sb.toString();
    }
}
