/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Book implements Serializable {

    private static final long serialVersionUID = 347926836;

    private Integer       bookId;
    private String        title;
    private Integer       dirId;
    private String        language;
    private String        series;
    private String        publisher;
    private LocalDateTime publishTime;
    private Short         rating;
    private Long          isbn10;
    private Long          isbn13;
    private Short         page;
    private String        format;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Book() {}

    public Book(Book value) {
        this.bookId = value.bookId;
        this.title = value.title;
        this.dirId = value.dirId;
        this.language = value.language;
        this.series = value.series;
        this.publisher = value.publisher;
        this.publishTime = value.publishTime;
        this.rating = value.rating;
        this.isbn10 = value.isbn10;
        this.isbn13 = value.isbn13;
        this.page = value.page;
        this.format = value.format;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Book(
        Integer       bookId,
        String        title,
        Integer       dirId,
        String        language,
        String        series,
        String        publisher,
        LocalDateTime publishTime,
        Short         rating,
        Long          isbn10,
        Long          isbn13,
        Short         page,
        String        format,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.bookId = bookId;
        this.title = title;
        this.dirId = dirId;
        this.language = language;
        this.series = series;
        this.publisher = publisher;
        this.publishTime = publishTime;
        this.rating = rating;
        this.isbn10 = isbn10;
        this.isbn13 = isbn13;
        this.page = page;
        this.format = format;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getBookId() {
        return this.bookId;
    }

    public Book setBookId(Integer bookId) {
        this.bookId = bookId;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Book setTitle(String title) {
        this.title = title;
        return this;
    }

    public Integer getDirId() {
        return this.dirId;
    }

    public Book setDirId(Integer dirId) {
        this.dirId = dirId;
        return this;
    }

    public String getLanguage() {
        return this.language;
    }

    public Book setLanguage(String language) {
        this.language = language;
        return this;
    }

    public String getSeries() {
        return this.series;
    }

    public Book setSeries(String series) {
        this.series = series;
        return this;
    }

    public String getPublisher() {
        return this.publisher;
    }

    public Book setPublisher(String publisher) {
        this.publisher = publisher;
        return this;
    }

    public LocalDateTime getPublishTime() {
        return this.publishTime;
    }

    public Book setPublishTime(LocalDateTime publishTime) {
        this.publishTime = publishTime;
        return this;
    }

    public Short getRating() {
        return this.rating;
    }

    public Book setRating(Short rating) {
        this.rating = rating;
        return this;
    }

    public Long getIsbn10() {
        return this.isbn10;
    }

    public Book setIsbn10(Long isbn10) {
        this.isbn10 = isbn10;
        return this;
    }

    public Long getIsbn13() {
        return this.isbn13;
    }

    public Book setIsbn13(Long isbn13) {
        this.isbn13 = isbn13;
        return this;
    }

    public Short getPage() {
        return this.page;
    }

    public Book setPage(Short page) {
        this.page = page;
        return this;
    }

    public String getFormat() {
        return this.format;
    }

    public Book setFormat(String format) {
        this.format = format;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Book setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public Book setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Book (");

        sb.append(bookId);
        sb.append(", ").append(title);
        sb.append(", ").append(dirId);
        sb.append(", ").append(language);
        sb.append(", ").append(series);
        sb.append(", ").append(publisher);
        sb.append(", ").append(publishTime);
        sb.append(", ").append(rating);
        sb.append(", ").append(isbn10);
        sb.append(", ").append(isbn13);
        sb.append(", ").append(page);
        sb.append(", ").append(format);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
