/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DirectoryPath implements Serializable {

    private static final long serialVersionUID = -148450614;

    private Integer       ancestor;
    private Integer       dirId;
    private Integer       pathLength;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public DirectoryPath() {}

    public DirectoryPath(DirectoryPath value) {
        this.ancestor = value.ancestor;
        this.dirId = value.dirId;
        this.pathLength = value.pathLength;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public DirectoryPath(
        Integer       ancestor,
        Integer       dirId,
        Integer       pathLength,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.ancestor = ancestor;
        this.dirId = dirId;
        this.pathLength = pathLength;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getAncestor() {
        return this.ancestor;
    }

    public DirectoryPath setAncestor(Integer ancestor) {
        this.ancestor = ancestor;
        return this;
    }

    public Integer getDirId() {
        return this.dirId;
    }

    public DirectoryPath setDirId(Integer dirId) {
        this.dirId = dirId;
        return this;
    }

    public Integer getPathLength() {
        return this.pathLength;
    }

    public DirectoryPath setPathLength(Integer pathLength) {
        this.pathLength = pathLength;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public DirectoryPath setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public DirectoryPath setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DirectoryPath (");

        sb.append(ancestor);
        sb.append(", ").append(dirId);
        sb.append(", ").append(pathLength);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
