/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Directory implements Serializable {

    private static final long serialVersionUID = -743031172;

    private Integer       dirId;
    private String        name;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Directory() {}

    public Directory(Directory value) {
        this.dirId = value.dirId;
        this.name = value.name;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Directory(
        Integer       dirId,
        String        name,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.dirId = dirId;
        this.name = name;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getDirId() {
        return this.dirId;
    }

    public Directory setDirId(Integer dirId) {
        this.dirId = dirId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Directory setName(String name) {
        this.name = name;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Directory setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public Directory setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Directory (");

        sb.append(dirId);
        sb.append(", ").append(name);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
