/*
 * This file is generated by jOOQ.
 */
package org.elegant.model.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Property implements Serializable {

    private static final long serialVersionUID = -697958747;

    private String        propName;
    private String        propValue;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Property() {}

    public Property(Property value) {
        this.propName = value.propName;
        this.propValue = value.propValue;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public Property(
        String        propName,
        String        propValue,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.propName = propName;
        this.propValue = propValue;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public String getPropName() {
        return this.propName;
    }

    public Property setPropName(String propName) {
        this.propName = propName;
        return this;
    }

    public String getPropValue() {
        return this.propValue;
    }

    public Property setPropValue(String propValue) {
        this.propValue = propValue;
        return this;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public Property setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
        return this;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public Property setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Property (");

        sb.append(propName);
        sb.append(", ").append(propValue);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
